version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  build:
    docker:
      - image: cimg/python:3.6.10
        environment:
          DATABASE_URL: postgresql://root@localhost/budget?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: budget
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      # - python/install-packages:
      #     args: coverage
      #     pkg-manager: pip
      #     pypi-cache: false
      - run:
          name: Test
          # command: ./manage.py test
          command: coverage run --source='.' manage.py test
      - run:
          name: Coverage
          command: coveralls

workflows:
  main:
    jobs:
      - build
