# Generated by Django 3.0.8 on 2020-09-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="card", max_length=100)),
                ("type", models.CharField(default="regular", max_length=100)),
                ("institution", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, max_length=100
                    ),
                ),
                ("number", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "accounts",},
        ),
    ]
