# Generated by Django 3.0.7 on 2020-07-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='institution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='card', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(default='regular', max_length=100),
        ),
    ]
