# Generated by Django 3.0.7 on 2020-07-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200721_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
