# Generated by Django 3.0.8 on 2020-08-07 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
        ("accounts", "0003_account_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categories", "0001_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tr_account",
                to="accounts.Account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="budget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tr_budget",
                to="budget.Budget",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tr_category",
                to="categories.Category",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tr_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
